### ISSUE TITLE
Player standing on objects causing flight

### ISSUE THREAD

**Issue by ottedam** [vr4vet/vr4vet#165] opened 2023-08-25 10:17 UTC
The holster can interact with objects in the environment. If you open a drawer for instance, the holster can be in the way of the drawer preventing it from opening fully. It can also bump against an open drawer closing the drawer by the physics. This should be removed.

**Comment by ingolvjr** [comment] 2023-08-28 07:50
@ottedam does this happen when the holster is empty?

**Comment by ingolvjr** [comment] 2023-08-28 07:51
I've tested and the holsters only have trigger colliders and everything in the holster have their colliders disabled (by default)

**Comment by ingolvjr** [comment] 2023-08-30 12:28
The issue is not the holster, but the player itself, it constantly tries to reposition itself to be on top of the closes collider underneath, which causes a sort of flight when you hold something underneath yourself because it recursively moves itself (and whatever it is holding) upwards

**Comment by ingolvjr** [comment] 2023-08-30 12:30
This probably also has something to do with the drawers opening or closing

**Comment by ingolvjr** [comment] 2023-08-30 12:31
https://github.com/vr4vet/vr4vet/assets/91453915/06bff2e4-e665-4403-b66d-3bde48403a1d


https://github.com/vr4vet/vr4vet/assets/91453915/b994d910-a735-47bf-8f2c-54057297fc00

**Closed** 2023-09-01 06:55 UTC
Labels: bug, help wanted

**Comment by ottedam** [comment] 2023-11-20 12:02
The fix is to add a layer to the objects and disable the physical interaction between the player and those layers
